### ISSUE TITLE
Boot loop after uninstall

### ISSUE THREAD

**Issue by CGDaveMac** [calasanmarko/TurboMac#8]
Used this kext with a bad battery on early 2015 13” MacBook Air and it brought the CPU from 29% to max successfully. Replaced the battery with third party from Amazon and decided to uninstall TurboMac. After running the uninstall script, I restarted and the computer went into a boot loop with “The computer restarted because of a problem” screen. 

So I re-installed Monterey over the existing install from recovery mode, and that worked, but CPU was back to being throttled at 29%.

I re-installed this kext, and everything was good again… this time I would just leave TurboMac on and merely ran the recommended “csrutil enable —without kext” and went right back to the same reboot loop.

**Comment by calasanmarko** [comment]
Hey. Since you're running Monterey could you try making sure that authenticated-root remains disabled after re-enabling SIP? Run `csrutil authenticated-root disable` from Recovery mode, if this turns out to be necessary I'll change the instructions accordingly.

As for why the CPU remains throttled - no idea. A reinstall from Recovery mode should remove all traces of this kext. Maybe an issue of some sort with the third-party battery not being recognized? Please mention it if you find out anything on this.

**Comment by CGDaveMac** [comment]
So I had already started to reinstall from Recovery Mode when I saw your response but I think I found the problem. On my initial install, I never got the pop up to approve the system extension, and when I rebooted, TurboMac worked but since SIP was off, it didn’t matter that the extension was approved. This time, I did get the pop-up, and with this as a guess as to the problem, I rebooted, and again everything was working. I then checked Security and Privacy and saw the extension waiting to be approved. 

Does that make sense? Since it’s working now and I would like to use the computer and not have to waste hours re-installing MacOS… let me know what you think before I go re-enable SIP.

**Comment by calasanmarko** [comment]
I think the issue is that when you re-enable authenticated-root, the changes the install script makes to the root volume get reverted, restoring the built-in throttling kexts and causing them to conflict with the TurboMac kext.

It could also be that trying to boot a modified root volume while authenticated root is enabled throws some sort of invisible error, as [this forum thread](https://forums.macrumors.com/threads/words-of-caution-regarding-modification-of-system-files-using-csrutil-authenticated-root-disable.2276764/) suggests.

You should be fine as long as you run both `csrutil enable --without-kext` and `csrutil authenticated-root disable`.

In a future release I'm going to make the TurboMac kext suppress the built-in throttling kexts instead of outright removing them at installation, making it possible to keep authenticated root enabled. But for now keep it off.

**Comment by CGDaveMac** [comment]
No problems after running both commands.
